### PR TITLE
Don't panic on unknown token_id in on_grpc_close.

### LINKED ISSUE #153: `hostcalls::open_grpc_stream` does not register closed streams, upstream failures result in panic
At the moment:
* `hostcalls::open_grpc_stream` only registers stream IDs when connections are successful
* Envoy calls close_grpc_stream on the stream id that is passed in, even when the original `open_grpc_stream` failed.
* `close_grpc_stream` can't route to the proper context and panics on `invalid token_id`

This seems to be an issue of ambiguous specification. I will open a PR to fix this, but it may be considered that Envoy is in the wrong here instead. Either way, we probably shouldn't panic.

Update:
* Envoy doesn't return the token ID, but still fires the on_close event. We will just need to ignore/log in on_grpc_close.

### PR DESCRIPTION
**Pull request by Protryon**
Fixes #153. 

This PR:
* Logs in `on_grpc_close` when an invalid `token_id` is sent from the host. This happens in Envoy when the initial connection fails.

### CODE REVIEW

**Comment by Protryon** [comment]
@PiotrSikora Any updates on this?

File: src/dispatcher.rs [hunk 1]
```diff
@@ -535,7 +536,7 @@ impl Dispatcher {
                 root.on_grpc_stream_close(token_id, status_code)
             }
         } else {
-            panic!("invalid token_id")
+            warn!("on_grpc_close: invalid token_id, a non-connected stream has closed");
```
Comment (PiotrSikora) [inline src/dispatcher.rs:539]: Since this is a known behavior, I'd lower this to the `trace` level.

Could you also add a TODO mentioning to restore the `panic` (maybe just comment it out) once the issue is fixed in Envoy?

Lastly, I'd really appreciate if you could open on issue with Envoy as well, since it should be fixed there.

**Comment by fmcato** [comment]
We might be hit by this when using unary grpc calls (seems to be triggered by invalid calls due to bad GRPC upstream configuration).

Let me know if I can help here.

File: src/dispatcher.rs (hunk 1 above)
Comment (Protryon) [reply src/dispatcher.rs]: @PiotrSikora Done. Changed log level to trace and added a TODO.

**Review by PiotrSikora — APPROVED** [review]
Could you merge with `master`? Thanks!
